#!/bin/bash
# Guillermo Narvaez

## Script variables - Product installation location
PRODUCT_INSTALL_PATH="${STUDIOUTILS_HOME}/product"
INSTALL_PATH="${PRODUCT_INSTALL_PATH}/tibco/sb-cep"
## Script variables - Builds installation location
BUILDS_INSTALL_PATH="${STUDIOUTILS_HOME}/builds"
## Script variables - Location for temporary workspaces
TEMP_DIR="${STUDIOUTILS_HOME}/temp_workspaces"
## Script variables - Location for *.ini files
INI_DIR="${STUDIOUTILS_HOME}/configuration"
## Script variables - Studio Configuration Area
STUDIO_CONFIGURATION_AREA="/Users/$USER/Library/Application Support/com.streambase.sb.sbstudio/"

function suggest() {
    CURR_LOC=$(pwd)
    if [ "${#COMP_WORDS[@]}" == "2" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[1]}" != -* ]]; then
            COMPREPLY=($(compgen -W "builds clean configs init install installs help m2 mondays" "${COMP_WORDS[1]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "m2" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            COMPREPLY=($(compgen -W "dev studio" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "install" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            # Could offer more advanced options here... looking at the actual svn tree?
            COMPREPLY=($(compgen -W "trunk sb/main/10.4 sb/main/10.5" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "help" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            COMPREPLY=($(compgen -W "builds clean configs init install installs help m2 mondays" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "help" ] && [ "${#COMP_WORDS[@]}" == "4" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[3]}" != -* ]]; then
            if [ "${COMP_WORDS[2]}" == "configs" ]; then
                COMPREPLY=($(compgen -W "rm" "${COMP_WORDS[3]}"))
            elif [ "${COMP_WORDS[2]}" == "installs" ]; then
                COMPREPLY=($(compgen -W "open rm path" "${COMP_WORDS[3]}"))
            elif [ "${COMP_WORDS[2]}" == "builds" ]; then
                COMPREPLY=($(compgen -W "install open rm" "${COMP_WORDS[3]}"))
            fi
        fi
    elif [ "${COMP_WORDS[1]}" == "configs" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            COMPREPLY=($(compgen -W "rm" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "configs" ] && [ "${#COMP_WORDS[@]}" == "4" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[3]}" != -* ]]; then
            if [ "${COMP_WORDS[2]}" == "rm" ]; then
                cd "$STUDIO_CONFIGURATION_AREA"
                COMPREPLY=($(compgen -d "${COMP_WORDS[3]}"))
                cd "$CURR_LOC"
            fi
        fi
    elif [ "${COMP_WORDS[1]}" == "builds" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            COMPREPLY=($(compgen -W "rm open install" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "builds" ] && [ "${#COMP_WORDS[@]}" == "4" ]; then
        # Don't allow words that start with '-'
        if [ "${COMP_WORDS[2]}" == "rm" ]; then
            if [[ "${COMP_WORDS[3]}" != -* ]]; then
                cd "$BUILDS_INSTALL_PATH"
                COMPREPLY=($(compgen -d "${COMP_WORDS[3]}"))
                cd "$CURR_LOC"
            fi
        elif [ "${COMP_WORDS[2]}" == "open" ]; then
            cd "$BUILDS_INSTALL_PATH"
            if [[ "${COMP_WORDS[3]}" == -* ]]; then
                if [[ "${COMP_WORDS[3]}" != "-" ]]; then
                    COMPREPLY="${COMP_WORDS[3]}"
                fi
            else
                COMPREPLY=($(compgen -d "${COMP_WORDS[3]}"))
            fi
            cd "$CURR_LOC"
        fi
    elif [ "${COMP_WORDS[1]}" == "builds" ] && [ "${#COMP_WORDS[@]}" == "5" ]; then
        if [ "${COMP_WORDS[2]}" == "open" ]; then
            cd "$BUILDS_INSTALL_PATH"
            if [ "${COMP_WORDS[3]}" == "-s" ]; then
                    COMPREPLY=($(compgen -d "${COMP_WORDS[4]}"))
            fi
            cd "$CURR_LOC"
        fi
    elif [ "${COMP_WORDS[1]}" == "installs" ] && [ "${#COMP_WORDS[@]}" == "3" ]; then
        # Don't allow words that start with '-'
        if [[ "${COMP_WORDS[2]}" != -* ]]; then
            COMPREPLY=($(compgen -W "open path rm" "${COMP_WORDS[2]}"))
        fi
    elif [ "${COMP_WORDS[1]}" == "installs" ] && [ "${#COMP_WORDS[@]}" == "4" ]; then
        # Don't allow words that start with '-'
        if [ "${COMP_WORDS[2]}" == "rm" ]; then
            if [[ "${COMP_WORDS[3]}" != -* ]]; then
                cd "$INSTALL_PATH"
                COMPREPLY=($(compgen -d "${COMP_WORDS[3]}"))
                cd "$CURR_LOC"
            fi
        elif [ "${COMP_WORDS[2]}" == "open" ]; then
            cd "$INSTALL_PATH"
            if [[ "${COMP_WORDS[3]}" == -* ]]; then
                if [[ "${COMP_WORDS[3]}" != "-" ]]; then
                    COMPREPLY="${COMP_WORDS[3]}"
                fi
            else
                COMPREPLY=($(compgen -d "${COMP_WORDS[3]}"))
            fi
            cd "$CURR_LOC"
        fi
    elif [ "${COMP_WORDS[1]}" == "installs" ] && [ "${#COMP_WORDS[@]}" == "5" ]; then
        if [ "${COMP_WORDS[2]}" == "open" ]; then
            cd "$INSTALL_PATH"
            if [ "${COMP_WORDS[3]}" == "-s" ]; then
                    COMPREPLY=($(compgen -d "${COMP_WORDS[4]}"))
            fi
            cd "$CURR_LOC"
        fi
    fi
}

complete -F suggest studioutils